#!/bin/bash

set -e

# Install native dependencies
apt update
apt install -y curl make

# Install bagop
curl -L -o /tmp/bagop "https://github.com/pojntfx/bagop/releases/latest/download/bagop.linux-$(uname -m)"
install /tmp/bagop /usr/local/bin

# Generate dependencies
make deps

# Build
CGO_ENABLED=0 bagop -j "$(nproc)" -b wakeup -x '(illumos/*|android/*|aix/*|ios/*|js/*|plan9)' 'main.go'

exit 0